### ISSUE TITLE
Need ability to update the email of a logged in user

### ISSUE THREAD

**Issue by davidjconnolly** [neroniaky/angular-token#156]
Hello,

I'm trying to allow my users to update their email addresses.  I'm doing this in a service using: 
```
updateUser(id, body) {
    return this._tokenService.put(this.usersResource + '/' + id, body);
  }

getCurrentUser() {
    return this._tokenService.validateToken();
  }
```

Then, in the calling component I have: 
```
// This passes in the existing user id & params (email, first_name, last_name)
//  to the userService updateUser function which calls me authed User update endpoint
this.userService.updateUser(params.id, params)
      .subscribe(
        data => {
          this.error = '';
          this.userService.getCurrentUser()
            .subscribe(
              res => {
                this.user = res.json().data;
                this.submitted = false;
              },
              error => {
                console.log('Error getting user ' + error);
              }
            );
        },
        error => {
          console.log('Error saving user ' + error);
          this.error = error;
          this.submitted = false;
        }
      );
```

I'm calling getCurrentUser after updateUser as a hack to try and update the local email address within the Angular2TokenService.  However, it's working intermittently.  What appears to be happening is my remote email changes on the serve but my local email (& thus uid) doesn't always get updated in Angular2TokenService so it tries to call validateToken with the old email/uid and I get a 401 error.

Is there a best practice or suggested approach for updating the email of a logged in user?

Thanks!

**Comment by davidjconnolly** [comment]
I found a workaround for anybody else having this issue:

```
  saveSettings(user) {
    this.submitted = true;

    // ToDo - Fix this hack
    let params: User = new User (
      user.id,
      user.first_name,
      user.last_name,
      user.email
    );

    this.userService.updateUser(params.id, params)
      .subscribe(
        data => {
          this.error = '';
          this.submitted = false;
          if (params.email != this._tokenService.currentUserData.email) {
            this._tokenService.currentUserData.email = params.email;
            this._tokenService.currentUserData.uid = params.email;
            this._tokenService.currentAuthData.uid = params.email;
            localStorage.setItem('uid', params.email);
          }
        },
        error => {
          console.log('Error saving user ' + error);
          this.error = error;
          this.submitted = false;
        }
      );
  }
```

Basically, after I update my user, I check to see if tokenService's uid/email is in sync with what I just changed, if it's not I update it manually.  Would be great to have an updateEmail (or similar) helper function the way you have for updatePassword.  Or potentially a helper for changing the UID value?

**Comment by neroniaky** [comment]
@davidjconnolly thanks for your explanation. Gonna take a look into this.

**Comment by rmcsharry** [comment]
Another - and more secure - option is after you submit the new email to the server, have the server send a confirmation email to that new address. When the request completes in Angular, call the Token2 logout method, which will destroy all the values in local storage.

Obviously provide a message to the user that they will be logged out and must confirm their new email address from the new inbox.

**Comment by neroniaky** [comment]
7.1.0-rc.0 exposes the UserData as BehaviorSubject. This allows the suer email to be updated. Please reopen if you are still having this problem.
