### ISSUE TITLE
Ability to use another routing library rather than the one angular provides

### ISSUE THREAD

**Issue by Verurteilt** [neroniaky/angular-token#160]
It would be awesome if we could use another library for routing with this library instead of the one angular provides, for example: https://ui-router.github.io/ng2/

**Comment by Verurteilt** [comment]
It's been a while since this, need any help with a PR?

**Comment by neroniaky** [comment]
Hey @Verurteilt, the router is used for `getAuthDataFromParams()` only. If you can make this function more universal another routing library would work. A PR would be much appreciated 😄 . Currently don't have the time to look for a solution myself.

**Comment by Verurteilt** [comment]
@neroniaky  It seems to be it's gonna be way more difficult than that because you use CanActivate, and it only works with the Router that comes with Angular 2, what do you think of separating this into a different class?

**Comment by guy-roberts** [comment]
I need this too. But before I try working on a PR to get angular-2-token working with the Ionic Router, has it already been done anywhere ? (Also, I am starting to wonder what all the ionic apps that use Devise Token Auth are working)

**Comment by guy-roberts** [comment]
@neroniaky, @Verurteilt  

I got basic requests woking with Ionic (not registration etc), just by removing the angular router.  

But the other thing is that angular-2-token provides its own set of http methods.  

I need to use Restangular, but of course the correct headers would not get sent by Restangular. So I would also need to change the way tokens are stored and used on the client.  With the original ng-token-auth, I think this was done with interceptors.   

Its complicated !

**Comment by guy-roberts** [comment]
Angular 4.3 has interceptors built in.  https://ryanchenkie.com/angular-authentication-using-the-http-client-and-http-interceptors.  So this is a way to store tokens and also to put them back into the http requests.

Although Ionic is not yet using Angular 4.3,  it seems to work by specifying this in package.json.

I'll post here if I get it all working sweetly.

**Comment by Verurteilt** [comment]
@guy-roberts  It's been a while since we finished the project we we doing with Angular2 (now we are currently doing 1 with React-Redux), I'll try this weekend to give a shot to this Issue and see if I can come up with a PR.

**Comment by neroniaky** [comment]
Angular Token 6+ supports interceptors. Please reopen when there are any questions left.
