### ISSUE TITLE
Not right installed from github

### ISSUE THREAD

**Issue by artem-galas** [neroniaky/angular-token#299]
Hi.
I want to get the latest changes that `master` branch contains, but I can't. As the version on npm differs from the version in master. 
I have also tried to install the package from github, but I am getting a different package content.
![8829d2abd3](https://user-images.githubusercontent.com/6387897/28019356-5d2fe100-6589-11e7-9b7c-183fe7a8e5d3.jpg)

**Comment by cybey** [comment]
Assuming you've tried this in your package.json:

    "dependencies": {
        "angular2-token": "git://github.com/neroniaky/angular2-token.git#master"
    }

**Comment by artem-galas** [comment]
Yes, I tried you example, but after install from git, I have not build package (on screeshot I don't have lib directory)

**Comment by cybey** [comment]
So what are you trying to achieve?
If you just want to use the dependency in your project, you're done. If you want to make changes, you have to clone (or fork) the repo. If you just clone it, you can point to it in your package.json like this:

    "dependencies": {
        "bar": "file:../foo/bar"
    }

If you fork it, and make changes, you can simply refer to it like in the example I gave you earlier, but it seems you've already done that.

This isn't an issue of this package.

**Comment by artem-galas** [comment]
I want to use the version from master branch, and not from npm.
The problem is if to install the package from github, its content doesn't contain  `lib` folder which is the main one for installing the package. It happens due to the fact the `build` script isn't running when you're installing the package from github.
On the screenshot I have shown what I am getting when trying to install the package via git, and here is the other screenshot displaying how the package looks like if to install it via npm.
![1500024881542](https://user-images.githubusercontent.com/6387897/28207215-81c7f498-6891-11e7-866d-e3e97c857a92.jpg)

**Comment by neroniaky** [comment]
Should be fixed with the newest ng-packgr. Please reopen if problem persists. Thank you.
