### ISSUE TITLE
Impossible to get user data

### ISSUE THREAD

**Issue by FeloVilches** [neroniaky/angular-token#401]
If the user is logged, it will access this if block. But also there's no data because it probably hasn't loaded yet, so it will print undefined. 

```javascript
if(this.authTokenService.userSignedIn()){
    // User is logged
    console.log(this.authTokenService.currentUserData);
    // prints "undefined"
}
```

**Comment by FeloVilches** [comment]
It seems the only possible way to get the user data when I need it is by calling validateToken *again* and subscribe to it.

**Comment by zamzam** [comment]
If init() could return an observable or something subscribable would be great, because right now you have to do 2 calls or retrieve data from localstorage manually

**Comment by ctilley83** [comment]
Unless I'm following the wrong process to access currentUserData, this is still broken.

**Comment by neroniaky** [comment]
We are working on making the UserData accessible via BehaviorSubject, which means you can just subscribe it.

**Comment by neroniaky** [comment]
UserData are now accessible as BehaviorSubject in version 7.1.0-rc.0. Please reopen / comment if this does not fix the problem. Thanks!
