### ISSUE TITLE
request method don't conform to http.request method.

### ISSUE THREAD

**Issue by glebmachine** [neroniaky/angular-token#406]
https://github.com/neroniaky/angular2-token/blob/3cdfb78686397591db0a8d620dccc14fb4369b27/src/angular2-token.service.ts#L366

Angular Http Service request method:
```ts
request(url: string | Request, options?: RequestOptionsArgs): Observable<Response>
```

Your request method:
```ts
request(options: RequestOptionsArgs): Observable<Response>
```

That's weird proxy =)

**Comment by sgruhier** [comment]
the worst part of request is the call to `this.handleResponse(response);` that subscribes to the observable. Very bad practice. This is why I stop using this project. I even tried to override some methods but they are private. :(

**Comment by sgruhier** [comment]
I switched to a custom, home made solution. I wanted to contribute more to that project, but hard to get time for that :(

**Comment by neroniaky** [comment]
Fixed with v6.x and the use of interceptors.
