### ISSUE TITLE
Live demo is not working

### ISSUE THREAD

**Issue by dks17** [neroniaky/angular-token#416]
> Quickstart includes the necessary forms and routing to quickly use Angular2-Token with your Project. A live demo can be found [here](https://angular2-token.herokuapp.com/#/session/sign-in).

It was found here:
[Clean readme & move doc](https://github.com/lynndylanhurley/devise_token_auth/pull/1129)

**Comment by neroniaky** [comment]
@dks17 Thanks, demo has been moved to stackblitz: https://stackblitz.com/github/neroniaky/angular-token
