### ISSUE TITLE
Rename Angular2-Token to Angular-Token

### ISSUE THREAD

**Issue by neroniaky** [neroniaky/angular-token#425]
All Angular versions > 2.0 should be named "Angular" instead of "Angular2".

- [x] Rename Github Repo
- [x] Rename NPM Package
- [x] Rename Module and Service

**Comment by raysuelzer** [comment]
Is this something that you want to do before releasing your updates for v6? I can help with with `rename module and service.`

**Comment by neroniaky** [comment]
Im not sure how to migrate best. Biggest Problem ist the Service name change because it’s not backwards compatible. According to Semver it should be 1.0.0, but I don’t know if we are there yet.

**Comment by raysuelzer** [comment]
I'm not quiet clear on the issue?  You could fork into a new repo for angular 5+?  Personally, I think it might make sense to release a 1.0.0 as a lot of people are already using this library and those who are still on Angular2 can continue to use the beta package.

**Comment by raysuelzer** [comment]
Any thoughts on this? Would be nice to not have to use rxjscompat.

**Comment by neroniaky** [comment]
@raysuelzer 0.2.0 implements RxJS 6.0 support. Could you give it a try?

**Comment by penguinwokrs** [comment]
@neroniaky Hello
Will Anuglar 5 + be developed as a separate repository?

**Comment by neroniaky** [comment]
@penguinwokrs we're not 100% sure yet, but I don't think we gonna split repos.

**Comment by xthilakx** [comment]
@neroniaky Is there anything I could do to help?

**Comment by neroniaky** [comment]
@xthilakx it would be nice if you could take a look at the README for the 6.0.0 branch an see if I missed anything, like still having `angular2` there.

**Comment by raysuelzer** [comment]
@neroniaky  the 6.0 version is working great. I followed the readme on there to upgrade, it was smooth.

**Comment by neroniaky** [comment]
Done! 🎉
