### ISSUE TITLE
angular-token@6.0.0 not working with FormData: Bad Request

### ISSUE THREAD

**Issue by NiekPas** [neroniaky/angular-token#453]
(Following up from #136)

After migrating to `angular-token@6.0.0-rc.0`, I'm still having issues with FormData requests to a Rails API backend. Using `angular2-token@0.2.0`, the issue was the absence of the FormData payload (see #136); now, the issue seems to be a malformed request.

**Sample code:**

    let formData = new FormData();
    formData.append('news_item', JSON.stringify(this.newsItem));
    return this.http.post('http://localhost:3000' + '/news_items', formData).subscribe(resp => {
      console.log(resp);
    }, error => {
      console.log(error);
    });

**Response:**

    {
        status: 400, 
        error: "Bad Request",
        exception : "#<ActionDispatch::Http::Parameters::ParseError: 743: unexpected token at '------WebKitFormBoundarymAL5BP3U2f06BDm1 ↵Content-Disposition: form-data; name="news_item" ↵ ↵{"title":"news item title","body":"news item body"} ↵------WebKitFormBoundarymAL5BP3U2f06BDm1-- ↵'>"
    }

Setting the `Content-Type` header explicitly makes no difference:

    let formData = new FormData();
    formData.append('news_item', JSON.stringify(this.newsItem));
    let headers = new HttpHeaders();
    headers.append('Content-Type', 'application/x-www-form-urlencoded');
    return this.http.post('http://localhost:3000' + '/news_items', formData, {headers: headers}).subscribe(resp => {
      console.log(resp);
    }, error => {
      console.log(error);
    });

**The issue goes away when I comment out the angular-token initialization**, that is, it works fine when I don't use `angular-token`:

    imports: [
      BrowserModule,
      HttpClientModule,
      //AngularTokenModule.forRoot({
        //apiBase: 'http://localhost:3000'
      //})
    ],

The issue seems to have something to do with rails receiving the entire request as a single string and choking on the parsing of that string, but importantly, **the error occurs before Rails calls the `create` action**; that is, the create action is never actually called.

I've seen [other issues](https://stackoverflow.com/questions/44677992/angular-2-http-post-using-httpinterceptor-unable-to-send-image-through-formdata) regarding Angular interceptors and FormData, but they are dissimilar from my issue in that there are not getting a `400 Bad Request`.

Let me know if you need any more info and I'll be happy to help.

**Comment by arjenbrandenburgh** [comment]
Has this been solved in version 6.0.0-rc.2?

**Comment by NiekPas** [comment]
No, but it has been in 6.0.0-rc.3! :tada:
