### ISSUE TITLE
How to delete/add headers on HTTP Service Wrapper

### ISSUE THREAD

**Issue by Awatatah** [neroniaky/angular-token#459]
Hello. So lets say I set the `globalOptions` to below:
```
globalOptions: {
    headers: {
        "Content-Type": "application/json",
        "Api-Key": "somevalue"
    }
}
```
and I need to use the **HTTP Service Wrapper** to execute a `post`,
How do I `delete` the "Content-Type" header only and preserve the rest?
I need to do this so my API will accept the formdata

**Comment by neroniaky** [comment]
Hey @Awatatah, thanks for your feedback. You can take a look at version 6.0, which uses interceptors which let you set the headers yourself. We're currently working on removing globalOptions entirely, because they should't be necessary with interceptors anymore.

**Comment by neroniaky** [comment]
Fixed with Version 6.x. Feel free to reopen.
