### ISSUE TITLE
Not setting the authenticated values successfully

### ISSUE THREAD

**Issue by sflang1** [neroniaky/angular-token#460]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior
Good morning! I'm working on a Angular - Ruby interaction, and I'm trying to get my authentication to work. By now, I know that if I perform a request through Postman or any other mean to /auth/sign_in, the result is successful. Then, executing the AngularTokenService signIn method also returns a correct response, however, this parameter is not updated in the authData variable, which means for Angular, the authentication is never performed. My Angular application has an structure more or less like this:
app/src/public/index/index.component.ts -> Here the login request is issued
app/src/private/dashboard/dashboard.component.ts -> I want to redirect here after a successful auth request
```typescript
this.tokenService.signIn({login: this.userEmail, password: this.password}).subscribe(
      res => {
        this.loading = false
        console.log(res)
        this.sessionService.email = res.body.data.email
        this.sessionService.loggedIn = true
        console.log(this.sessionService)
        this.router.navigate(['private', 'dashboard'], {relativeTo: this.route})
      },
      error => {
        this.loading = false
        console.log(error)
      }
    )
```
The private module states AngularTokenService as canActivate
```typescript
const routes: Routes = [
    {path: '', loadChildren: './public/public.module#PublicModule'},
    { path: 'private', loadChildren: './private/private.module#PrivateModule', canActivate: [AngularTokenService]}
]
```
## Expected behavior
The expected behavior should be that after a valid request, the AngularTokenService works as a canActivate and allows me to navigate to /private because the canActivate condition is true, and also that the following requests should be authenticated

## Environment

Angular-Token version: 6.0.0-rc.4
Angular version: 

Bundler
- [x] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [x] Chrome (desktop) version  63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by sflang1** [comment]
I realized the trouble's solution was in the common problems. I'm so sorry

**Comment by neroniaky** [comment]
Thanks for taking the time to fill out the the bug report this detailed :)!
