### ISSUE TITLE
RegisterAccount not sending same data

### ISSUE THREAD

**Issue by Grafexy** [neroniaky/angular-token#462]
## I'm submitting a...
- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior

```
this.tokenService.registerAccount({
      first_name: user.first_name,
      last_name: user.last_name,
      login: user.email,
      password: <string>user.password,
      passwordConfirmation: <string>user.password_confirmation,
});
```

but it will send only 

```
    const body = {
      [this.options.loginField]: registerData.login,
      password: registerData.password,
      password_confirmation: registerData.password_confirmation,
    };
```

https://github.com/neroniaky/angular-token/blob/master/projects/angular-token/src/lib/angular-token.service.ts#L153

## Expected behavior
In token version 0.2.0 we would send whole data
https://github.com/neroniaky/angular-token/blob/v0.2.0/src/angular2-token.service.ts#L169

## What is the motivation / use case for changing the behavior?
Devise token can receive more data then loginField, password and password_confirmation.
In our case User must have first name, and last name

## Environment

Angular-Token version: 6.0.0
Angular version: 6.0.3

Bundler
- [x] Angular CLI (Webpack)
- [x] Webpack
- [x] SystemJS

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by neroniaky** [comment]
Fix got merged and published in Version 6.0.2. Please reopen if problem still persists.
