### ISSUE TITLE
Docs: Incorrect function signature for resetPassword method

### ISSUE THREAD

**Issue by xthilakx** [neroniaky/angular-token#468]
## I'm submitting a...

- [x] Documentation issue or request

## Current behavior
Doc for [Session Management Reset Password](https://github.com/neroniaky/angular-token/wiki/session-management#resetpassword
) says: 
`resetPassword({email: string, userType?: string}): Observable<Response>`

### Example
```typescript
this.tokenService.resetPassword({
    email: 'example@example.org',
}).subscribe(
    res =>      console.log(res),
    error =>    console.log(error)
);
```
but [interface ResetPasswordData](https://github.com/neroniaky/angular-token/blob/master/projects/angular-token/src/lib/angular-token.model.ts#L30) shows a different function signature:

```typescript
export interface ResetPasswordData {
  login:                  string;
  userType?:              string;
}
```

## Expected behavior
I expect function signature in type definitions and the documentation to be consistent as this may confuse those who are trying to integrate this package into their application. 

## Environment

Angular-Token version: 6.0.2

**Comment by neroniaky** [comment]
Good find! You want to create a PR?

**Comment by xthilakx** [comment]
@neroniaky Sure!

**Comment by neroniaky** [comment]
Forgot that the docs are a wiki now, so no PR. Changed it. Thanks!
