### ISSUE TITLE
Build fails when used in Angular Universal applications

### ISSUE THREAD

**Issue by xthilakx** [neroniaky/angular-token#470]
https://github.com/neroniaky/angular-token/blob/044e5160ffddb0e4fb260ef89ffd1c344f423134/projects/angular-token/src/lib/angular-token.service.ts#L73

Reference to the window object makes it impossible to use angular-token on Angular Universal applications. 

Would you accept the pull request, if I inject PLATFORM_ID to conditionally mock the reference to window.location while rendering on the server side? 

Something like this:
````typescript
constructor(
    @Inject(PLATFORM_ID) private platformId: Object
) {
    this.isServerSideRendering = isPlatformServer(platformId);

    if (this.isServerSideRendering) {
        // mock window.location
    }

}
````

**Comment by arjenbrandenburgh** [comment]
I would be fine with this. @neroniaky?

**Comment by neroniaky** [comment]
@arjenbrandenburgh sure :)

**Comment by arjenbrandenburgh** [comment]
@xthilakx, could you make a PR for this?
