### ISSUE TITLE
angular-token.js 'inject' was not found in '@angular/core'

### ISSUE THREAD

**Issue by Sikachyna** [neroniaky/angular-token#472]
## I'm submitting a...

- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior
WARNING in ./node_modules/angular-token/fesm5/angular-token.js
663:161-167 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/angular-token/fesm5/angular-token.js
663:181-187 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/angular-token/fesm5/angular-token.js
663:212-218 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/angular-token/fesm5/angular-token.js
663:239-245 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/angular-token/fesm5/angular-token.js
663:61-77 "export 'defineInjectable' was not found in '@angular/core'

## Expected behavior
Building without problem

## Environment

Angular-Token version: 0.2.0
Angular version: 5.2.11

Bundler
- [x] Angular CLI (Webpack)
- [x] Webpack
- [ ] SystemJS

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.1.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by neroniaky** [comment]
Should be fixed in newest version
