### ISSUE TITLE
Please add v0.2.0 tag to the repository

### ISSUE THREAD

**Issue by x-yuri** [neroniaky/angular-token#473]
Otherwise it's hard to learn what exactly switching to v0.2.0 means.

**Comment by neroniaky** [comment]
@x-yuri could you please elaborate. Thanks!
v0.2.0 is an older version of this library, so you should switching to v6.x

**Comment by x-yuri** [comment]
@neroniaky I was trying to see what this repository looked like at version 0.2.0. But there's no such tag in this repository. So, no easy way. I was particularly interested in a state that was published to npm. If you were to add missing tags, or at least add tags (that correspond to a state published to npm) in the future, that would be awesome.

**Comment by arjenbrandenburgh** [comment]
https://github.com/neroniaky/angular-token/tree/v0.2.0

How about this branch?

**Comment by x-yuri** [comment]
@arjenbrandenburgh Are you sure it's what one would get if he/she were to install `angular2-token@0.2.0`? What about other versions?

```
6.0.2
6.0.1
6.0.0-rc.4
6.0.0-rc.3
6.0.0-rc.2
6.0.0-rc.0
```

I'm just asking to make life easier for users. One might want to confirm if some bug was fixed in one particular version. Being able to do so without cloning the repository is a good thing to have, isn't it? There might be other use cases.

**Comment by neroniaky** [comment]
Just published 6.0.3. Didn't create releases for the last versions before. Sorry, will get better in the future 😃 .

**Comment by neroniaky** [comment]
Alright, closing this for now.
