### ISSUE TITLE
Not possible to dynamically set apiBase

### ISSUE THREAD

**Issue by quentinbt** [neroniaky/angular-token#475]
## I'm submitting a...

- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior

Its not possible to change the apiBase from AngularTokenService via the init method as before

## What is the motivation / use case for changing the behavior?

I'm using angular-token with rails devise auth + apartment, so my subdomain (tenant)  from the apiBase might change
my frontend and backend are not on the same domain origin so without the init method from tokenService its not possible to dynamically change the subdomain (and query another schema than the one init in appModule)

## Environment

Angular-Token version: 6.0.2
Angular version: 6.1.6

Bundler
- [x] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

**Comment by neroniaky** [comment]
@quentinbt thank you for creating this issue. Adding an setter and  and possibly getter for AngularTokenOptions would be a good thing to have.

You willing to create an PR @quentinbt ?

**Comment by musienkoyuriy** [comment]
As a temporary solution we use this in app.component constructor:

 `(this.authToken as any).options.apiBase = environment.api_endpoint;`

**Comment by neroniaky** [comment]
Setter and getter added in PR #478
