### ISSUE TITLE
Not sure if this library will work with Rails 5.2?

### ISSUE THREAD

**Issue by rmcsharry** [neroniaky/angular-token#482]
I just read this [SO question](http://1.yqwk.win/?questions/51304392/rails-actioncontroller-ignores-request-headers) and the answer from messanjah.

It seems in the future all headers will have to be of the format "HTTP_x_"

So I wonder if anyone who upgrades their API to Rails 5.2 might run into problems if they are still using this library?

If so perhaps the readme should be updated to indicate this (or warn of this)?

Or would it require a change in the devise_auth_gem - or even both libraries?

**Comment by neroniaky** [comment]
I have a project using Rails 5.2 and haven’t run into any issues yet. Not much we can do on the rails side of things, but if gets update we definitely have to do so too. Do you have a link for me?

**Comment by rmcsharry** [comment]
@neroniaky Thanks for confirming it still works. I must have misunderstood that SO answer, so I checked the Rails 5.2 release notes and find no mention of this. So we are ok it seems to me. Closing.
