### ISSUE TITLE
Cannot find module 'angular-token'

### ISSUE THREAD

**Issue by dkrusenstrahle** [neroniaky/angular-token#485]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior
I have installed the module with npm install angular-token but when I try to import the module then I got: src/app/app.module.ts(21,36): error TS2307: Cannot find module 'angular-token'.

Using:

import { AngularTokenModule } from 'angular-token';

## Expected behavior
I should be able to import using the instruction from documentation.

## Environment

Angular-Token version: 7.0.0
Angular version: 7.0.0

Bundler
- [x ] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [x ] Chrome (desktop) version 71.0.3578.98
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by voidjj** [comment]
I have the same problem

**Comment by Mat1s** [comment]
I also have the same problem

**Comment by neroniaky** [comment]
Thanks for reporting. Gonna take a look into it. Does downgrading to 7.0.0-rc.0 help?

**Comment by neroniaky** [comment]
Just published 7.0.1, please give it a try. Thank you!
