### ISSUE TITLE
Omniauth from electron app

### ISSUE THREAD

**Issue by pradosh987** [neroniaky/angular-token#495]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Performance issue
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Current behavior

I am little confused how to use oauth signin from electron app. I am currently using 
```
this.tokenService.signInOAuth(
'github'
).subscribe(
  res =>      console.log(res),
  error =>    console.log(error)
);
```
 which open up electron window. I am sure its unsafe this way. So how to get oauth url and open it in browser window instead?

## Environment

Angular-Token version: 7.0.1
Angular version: 7.3.1

Bundler
- [x] Angular CLI (Webpack)
- [ ] Webpack
- [ ] SystemJS

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by neroniaky** [comment]
I haven't looked at electron apps yet. My guess is, that this is a feature (customize the OAuth window) Angular-Token doesn't support yet.
