### ISSUE TITLE
Is there an ability to set currentUserData?

### ISSUE THREAD

**Issue by artem-galas** [neroniaky/angular-token#59]
For example, I have this code snippet:
```ts
this._tokenService
      .put(`${environment.API}/auth/invitation`, form.value)
      .subscribe(res => {
       //Trow error
        this._tokenService.currentUserData = res.json().data;
      });
```

Or for example, I am using `_tokenService.currentUserData?.username` in header and I can update the current user username, but the value in header won't change.

How can I update `currentUserData`?

Thanks for your advance :)

**Comment by neroniaky** [comment]
@artem-galas thanks a lot for your issue and the PR. Please help me to understand your use case a little more.
`currentUserData` is send and maintained by the backend/devise token auth. You could modify it in the browser, but the next time you load it from the backend it would be the old value.

**Comment by artem-galas** [comment]
For example we have a header which uses a username of a user. The user can change it and once he changed, we should display a new username in the header.

Other use case I am trying to implement now is the next one: it's `accept invitation`.
Once a user follows the link from the email, he'll be directed to the page where he should type his password and password_confirmation.
Then he should be authenticated in the system and be provided with the edit page where he can type such data as username/full name etc. 
To implement this I am using this `this._tokenService.validateToken()` Meaning, I am sending the request to the server, which updates the `currentUserData`. If we have a setter for this, I will need to make an extra request to the server.

Code Example I have now:

```ts
acceptInvite(form) {
    this._tokenService
      .put(`/auth/invitation`, form.value)
      .subscribe(res => {
        let user = res.json().data;
        this._tokenService.validateToken()
          .subscribe(() => {
            this.router.navigate(['/team/users', user.id, 'edit'])
          });
      });
  }
```

Code Example I would like:

```ts
acceptInvite(form) {
    this._tokenService
      .put(`/auth/invitation`, form.value)
      .subscribe(res => {
        let user = res.json().data;
        this._tokenService.currentUserData = user
        this.router.navigate(['/team/users', user.id, 'edit'])
      });
  }
```

**Comment by neroniaky** [comment]
7.1.0-rc.0 exposes the UserData as BehaviorSubject. This means you can now subscribe and change the UserData as desired. Please reopen if problem still exists.
